image: node:12.14.0

stages:
  - build
  - upload

before_script:
  - export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - VERSION_TAG=${VERSION}
  - OSS_URL=${CDN_OSS_DAILY}

build:docker:
  when: manual
  stage: build
  image: docker:latest
  script:
    - docker build -t authing:docs-new .
    - mkdir docker-image
    - docker save -o docker-image/${CI_PROJECT_NAME}-${VERSION_TAG}-docker.tar authing:docs-new
  artifacts:
    untracked: false
    paths:
      - docker-image
    expire_in: 3 days

upload:docker:
  when: manual
  stage: upload
  image: docker:latest
  script:
    - docker load < docker-image/${CI_PROJECT_NAME}-${VERSION_TAG}-docker.tar
    - docker login -u ${DOCKER_USERNAME}  -p ${DOCKER_PASSWD}  ${DOCKER_REPO}
    - export IMAGE_NAME=${DOCKER_REPO}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
    - docker tag authing:docs-new ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:latest
  dependencies:
    - build:docker
